/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EjercicioJEditorPaneVentanaAux.java
 *
 * Created on 21-abr-2010, 16:16:39
 */

package EjerciciosSwing;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author atorre
 */
public class EJ116EjercicioJEditorPaneVentanaAux extends javax.swing.JFrame {

    /** Creates new form EjercicioJEditorPaneVentanaAux */
    public EJ116EjercicioJEditorPaneVentanaAux(String URL) {
        initComponents();
        try {
            jEditorPane1.setPage(URL);
        } catch (IOException ex) {
            // Esto lo añade automáticamente cuando intentamos añadir
            // la sentencia jEditorPane1.setPage(URL); y en la bombillita que
            // sale le decimos que rodee la sentencia de un bloque Try-Catch
            // para capturar la excepción.
            Logger.getLogger(EJ116EjercicioJEditorPaneVentanaAux.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contenido de la URL");

        jScrollPane1.setViewportView(jEditorPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
