/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EjercicioJSpinner.java
 *
 * Created on 21-abr-2010, 21:01:42
 */

package EjerciciosSwing;

/**
 *
 * @author atorre
 */
public class EJ150EjercicioJSpinner extends javax.swing.JFrame {

    /** Creates new form EjercicioJSpinner */
    public EJ150EjercicioJSpinner() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio JSpinner");
        getContentPane().setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Mes:");
        getContentPane().add(jLabel1);

        jSpinner1.setModel(new javax.swing.SpinnerListModel(new String[] {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"}));
        getContentPane().add(jSpinner1);

        jLabel2.setText("Año:");
        getContentPane().add(jLabel2);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(2010, 1900, 2100, 1));
        getContentPane().add(jSpinner2);

        jLabel3.setText("Otra fecha distinta:");
        getContentPane().add(jLabel3);

        jSpinner3.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(956344200000L), new java.util.Date(1587496200000L), java.util.Calendar.MONTH));
        jSpinner3.setEditor(new javax.swing.JSpinner.DateEditor(jSpinner3, "MM/yyyy"));
        getContentPane().add(jSpinner3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EJ150EjercicioJSpinner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    // End of variables declaration//GEN-END:variables

}
